In [2]:
import pandas as pd
df = pd.read_csv("../data/raw/tickets.csv")
df.head()

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51,Security,Outage,Disruption,Data Breach,NaN,NaN,NaN,NaN
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN

In [3]:
df.shape

(28587, 16)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28587 entries, 0 to 28586
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   24749 non-null  str
 1   body      28587 non-null  str
 2   answer    28580 non-null  str
 3   type      28587 non-null  str
 4   queue     28587 non-null  str
 5   priority  28587 non-null  str
 6   language  28587 non-null  str
 7   version   28587 non-null  int64
 8   tag_1     28587 non-null  str
 9   tag_2     28574 non-null  str
 10  tag_3     28451 non-null  str
 11  tag_4     25529 non-null  str
 12  tag_5     14545 non-null  str
 13  tag_6     5874 non-null   str
 14  tag_7     2040 non-null   str
 15  tag_8     565 non-null    str
dtypes: int64(1), str(15)
memory usage: 3.5 MB

In [6]:
df.isnull().sum()

subject      3838
body            0
answer          7
type            0
queue           0
priority        0
language        0
version         0
tag_1           0
tag_2          13
tag_3         136
tag_4        3058
tag_5       14042
tag_6       22713
tag_7       26547
tag_8       28022
dtype: int64

In [12]:
df[["subject", "body", "type", "queue", "priority", "language", "answer"]].head()

,subject,body,type,queue,priority,language,answer
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Incident,Technical Support,high,de,Vielen Dank für die Meldung des kritischen Sic...
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",Incident,Technical Support,high,en,"Thank you for reaching out, <name>. We are awa..."
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Request,Returns and Exchanges,medium,en,Thank you for your inquiry. Our products suppo...
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",Request,Billing and Payments,low,en,We appreciate you reaching out with your billi...
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Problem,Sales and Pre-Sales,medium,en,Thank you for your inquiry. Our product suppor...

In [8]:
df["type"].value_counts()

type
Incident    11466
Request      8187
Problem      6012
Change       2922
Name: count, dtype: int64

In [13]:
df["queue"].value_counts()

queue
Technical Support                  8362
Product Support                    5252
Customer Service                   4268
IT Support                         3433
Billing and Payments               2788
Returns and Exchanges              1437
Service Outages and Maintenance    1148
Sales and Pre-Sales                 918
Human Resources                     576
General Inquiry                     405
Name: count, dtype: int64

In [16]:
pd.crosstab(df["type"], df["queue"])

queue,Billing and Payments,Customer Service,General Inquiry,Human Resources,IT Support,Product Support,Returns and Exchanges,Sales and Pre-Sales,Service Outages and Maintenance,Technical Support
type,,,,,,,,,,
Change,159,321,120,30,584,601,188,154,273,492
Incident,674,1074,117,316,1244,2306,568,203,630,4334
Problem,615,904,77,57,870,1149,290,119,79,1852
Request,1340,1969,91,173,735,1196,391,442,166,1684

In [9]:
df["priority"].value_counts()

priority
medium    11515
high      11178
low        5894
Name: count, dtype: int64

In [10]:
df["language"].value_counts()

language
en    16338
de    12249
Name: count, dtype: int64

In [11]:
df["body_length"] = df["body"].astype(str).apply(len)
df["body_length"].describe()

count    28587.000000
mean       387.263896
std        200.129011
min          6.000000
25%        219.000000
50%        386.000000
75%        551.000000
max       1469.000000
Name: body_length, dtype: float64

## Day 1 Conclusion

The dataset contains multilingual customer support tickets in English and German.

Two useful prediction targets are available:

1. 'type': represents the nature of the ticket, such as Incident, Request, Problem, or Change.
2. 'queue': represents the team or department that should handle the ticket, such as Technical Support, Billing and Payments, or Sales and Pre-Sales.

For the baseline system, I will use 'subject + body' as input text.

Two baseline models will be built:

- Ticket Type Classifier: 'subject + body → type'
- Ticket Queue Classifier: 'subject + body → queue'

The 'answer' column will not be used as input because it represents the support response and can cause data leakage.

The 'priority' column will be used later for urgency detection.