In [4]:
import pandas as pd
import re
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv("../data/raw/tickets.csv")

In [6]:
df = df[["subject", "body", "type", "queue", "priority", "language"]].copy()

In [7]:
df["subject"] = df["subject"].fillna("")
df["body"] = df["body"].fillna("")

In [8]:
df["text"] = df["subject"] + " " + df["body"]

In [9]:
print(type(df['text'][0]))

<class 'str'>

In [18]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    return text

In [19]:
df["clean_text"] = df["text"].apply(clean_text)

In [20]:
df = df[df["clean_text"].str.len() > 0]

In [21]:
train_df, test_df = train_test_split(
    df[["clean_text", "type", "queue", "priority", "language"]],
    test_size=0.2,
    random_state=42,
    stratify=df["type"]
)

In [22]:
train_df.to_csv("../data/processed/train.csv", index=False)
test_df.to_csv("../data/processed/test.csv", index=False)

In [23]:
type_names = sorted(df["type"].unique())

type_mapping = pd.DataFrame({
    "class_id": range(len(type_names)),
    "type": type_names
})

type_mapping.to_csv("../data/processed/type_mapping.csv", index=False)

type_mapping

   class_id      type
0         0    Change
1         1  Incident
2         2   Problem
3         3   Request

In [24]:
queue_names = sorted(df["queue"].unique())

queue_mapping = pd.DataFrame({
    "class_id": range(len(queue_names)),
    "queue": queue_names
})

queue_mapping.to_csv("../data/processed/queue_mapping.csv", index=False)

queue_mapping

   class_id                            queue
0         0             Billing and Payments
1         1                 Customer Service
2         2                  General Inquiry
3         3                  Human Resources
4         4                       IT Support
5         5                  Product Support
6         6            Returns and Exchanges
7         7              Sales and Pre-Sales
8         8  Service Outages and Maintenance
9         9                Technical Support